#!/usr/bin/env bash
#This script prints "Best School" 10 times but for the 9th iteration prints "Hi"
count=1
while [ $count -le 10 ]; do
	if [ $count -eq 9 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
		count=$((count+1))
done
