#!/usr/bin/env bash
#This scripts displays content of cwd in list format
for file in *; do
    # Check if the file is a regular file && not hidden
    if [ -f "$file" ] && [[ $file != .* ]]; then
        # Extract the part of the name after the first dash
        name_after_dash=$(echo "$file" | cut -d '-' -f 2-)
        echo "$name_after_dash"
    fi
done
