#!/usr/bin/env bash
#This scripts checks if file "school exists"
file_path="school"

if [ -e "$file_path" ]; then
    echo "school file exists"

    if [ -s "$file_path" ]; then
        echo "school file is not empty"

        if [ -f "$file_path" ]; then
            echo "school is a regular file"
        fi
    else
        echo "school file is empty"
    fi
else
    echo "school file does not exist"
fi
